CREATE DATABASE in2db;
CREATE USER in2db WITH PASSWORD 'in2db';
GRANT ALL PRIVILEGES ON DATABASE in2db TO in2db;

CREATE DATABASE in2dbutest;
CREATE USER in2dbutest WITH PASSWORD 'in2dbutest';
GRANT ALL PRIVILEGES ON DATABASE in2dbutest TO in2dbutest;